# This workflow compiles the audio project with cmake
# Workflow credit to: https://github.com/actions/starter-workflows/issues/196

name: Compile

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on: [push]

# Executes cmake
jobs:
  build-ubuntu:

      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v1
      - name: configure
        run:  sudo apt install libasound2-dev && sudo apt install libdbus-1-dev && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8 && mkdir build && cd build && cmake ..
      - name: build
        run: make
